apiVersion: v2
name: nginx-demo
description: A simple nginx demo application with Ingress and TLS
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - nginx
  - demo
  - k3s
  - rke2
home: https://github.com/antoniopicone/lazykube
maintainers:
  - name: LazyKube
